global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-notifications'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'telegram-notifications'
    telegram_configs:
      - bot_token: '8395433352:AAEIvIuX7cJ-_is2NbCjs7uA0-QF3e_eoTY'
        chat_id: 5377484616
        parse_mode: 'Markdown'
        message: |
          ğŸš¨ *Alert:* {{ .CommonLabels.alertname }}
          ğŸ” *Instance:* {{ .CommonLabels.instance }}
          ğŸ“Š *Severity:* {{ .CommonLabels.severity }}
          ğŸ•’ *Time:* {{ .StartsAt }}
          ğŸ’¬ {{ .Annotations.description }}

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
