global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager_inforadar:9093

rule_files:
  - "alert.rules.yml"
  - "test.rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus_inforadar:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node_exporter_inforadar:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor_inforadar:8080"]

  - job_name: "mysql"
    static_configs:
      - targets: ["mysql_inforadar:9104"]

  - job_name: "inforadar_ui"
    static_configs:
      - targets: ["inforadar_ui:5000"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana_inforadar:3000"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki_inforadar:3100"]
