groups:
  - name: TelegramTest
    rules:
      - alert: TelegramConnectionTest
        expr: vector(1)
        for: 10s
        labels:
          severity: info
        annotations:
          summary: "üöÄ –¢–µ—Å—Ç–æ–≤–æ–µ —É–≤–µ–¥–æ–º–ª–µ–Ω–∏–µ –≤ Telegram"
          description: "–ï—Å–ª–∏ —Ç—ã –ø–æ–ª—É—á–∏–ª —ç—Ç–æ —Å–æ–æ–±—â–µ–Ω–∏–µ ‚Äî –≤—Å—ë —Ä–∞–±–æ—Ç–∞–µ—Ç –∫–æ—Ä—Ä–µ–∫—Ç–Ω–æ!"
