global:
  resolve_timeout: 5m

route:
  receiver: "telegram"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h

receivers:
  - name: "telegram"
    telegram_configs:
      - bot_token: "<小孝鞋_小_BOT_TOKEN>"
        chat_id: <小孝鞋_小_CHAT_ID>
        parse_mode: "Markdown"
        message: |
           *{{ .CommonLabels.alertname }}*
          *Instance:* {{ .CommonLabels.instance }}
          *Severity:* {{ .CommonLabels.severity }}
          *Summary:* {{ .CommonAnnotations.summary }}
          *Time:* {{ .StartsAt }}
